spring:
  application:
    name: heart-beat-live

  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      database: heart-beat-app
      username: mongodb
      password: password

  graphql:
    websocket:
      path: /graphql/websocket

auth:
  firebase:
    function:
      token: "simple-firebase-function-token"
#    service-account-file: classpath:service-account.json

app:
  subscription:
    free:
      max-sharing-codes-limit: 2
      max-subscribers-limit: 1
      max-subscriptions-limit: 1
    pro:
      max-sharing-codes-limit: 20
      max-subscribers-limit: 30
      max-subscriptions-limit: 30
  sharing-code:
    sharing-url-template: "https://heartbeatlive.com/sharing/%s"
  heart-rate-stream:
    heart-rate-time-to-send: PT1M
    subscriptions-count-limit-per-user: 15