spring:
  application:
    name: heart-beat-live

  data:
    mongodb:
      uri: mongodb://localhost:27017/heart-beat-app
      username: mongodb
      password: password

auth:
  firebase:
    function:
      token: "simple-firebase-function-token"
#    service-account-file: classpath:service-account.json