spring:
  application:
    name: heart-beat-live

  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      database: heart-beat-app
      username: mongodb
      password: password

auth:
  firebase:
    function:
      token: "simple-firebase-function-token"
#    service-account-file: classpath:service-account.json