spring:
  application:
    name: heart-beat-live

  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      database: heart-beat-app
      username: mongodb
      password: password

  graphql:
    websocket:
      path: /graphql/websocket

  messages:
    basename: i18n/push_notifications
    encoding: UTF-8

server:
  port: ${PORT:8080}

auth:
  firebase:
    function:
      token: "simple-firebase-function-token"

one-signal:
  rest-api-key: ""
  app-id: ""

cache:
  user-subscribers:
    entry-capacity: 1_000_000
    idle-scan-time: PT30S

app:
  subscription:
    free:
      displayName:
        en: Free
        ru: Бесплатная
      limits:
        max-sharing-codes-limit: 2
        max-subscribers-limit: 1
        max-subscriptions-limit: 1
        receive-heart-rate-match-notification: false
      info:
        description-items:
          en:
            - Fully free
            - One free subscription
            - One free subscriber
          ru:
            - Полностью бесплатно
            - Одна бесплатная подписка
            - Один бесплатный подписчик
    pro:
      displayName:
        en: Premium
        ru: Премиум
      limits:
        max-sharing-codes-limit: 20
        max-subscribers-limit: 30
        max-subscriptions-limit: 30
        receive-heart-rate-match-notification: true
      prices:
        - price: 5
          currency: USD
          duration: P31D
          refund-duration: P3D
          old-price: 10
#          stripe-price-id: "price_1"
        - price: 2
          currency: USD
          duration: P7D
          refund-duration: P1D
          old-price: 5
#          stripe-price-id: "price_2"
      info:
        description-items:
          en:
            - Up to 30 subscriptions
            - Up to 30 subscribers
            - Heart rate match notifications
          ru:
            - До 30 подписчиков
            - До 30 подписок
            - Уведомления о совпадении сердцебиения
  user:
    reset-password-request-timeout: PT1M
  sharing-code:
    sharing-url-template: "https://heartbeatlive.com/sharing/%s"
  heart-rate-stream:
    heart-rate-time-to-send: PT1M
    subscriptions-count-limit-per-user: 15
    store-user-heart-rate-duration: PT40S
    high-low-push:
      send-push-timeout-duration: PT5M
      normal-heart-rate:
        min: 31
        max: 179
    heart-rate-match-push:
      send-push-timeout-duration: PT5M
      include-heart-rates-for-duration: PT30S

payment:
  stripe:
    enabled: false
    payment-requires-action-window: PT32H
#    public-api-key: ""
#    private-api-key: ""
#    webhook-endpoint-secret: ""

#apple:
#  app-ids:
#    - "XXX.com.munoon.heartbeatlive"
#    - "YYY.com.munoon.heartbeatlive"