introspection:
  schemaFile: ../src/main/resources/graphql/**/*.graphqls
  metadataFile: ./metadata.json

info:
  title: HeartBeatLive GraphQL API
  description: |
    API documentation of HeartBeatLive server \
    [GitHub Repository](https://github.com/HeartBeatLive/HeartBeatLiveServer) \
    [Schema File](/schema.graphqls)
  version: "1.0"
  x-introItems:
    - title: GitHub Repository
      url: https://github.com/HeartBeatLive/HeartBeatLiveServer
    - title: Schema File
      url: /schema.graphqls

servers:
  - url: http://localhost:8080/graphql
    description: Local Server
    production: false
    headers:
      - name: Content-Type
        example: application/graphql+json
        comment: Content type must be provided
      - name: Authorization
        example: Bearer <USER_TOKEN>
        comment: Your authentication token (Optional)
      - name: X-Application-Type
        example: <USER_APPLICATION_TYPE>
        comment: Application type, from which user makes requests (Optional)
      - name: X-Application-Version
        example: <USER_APPLICATION_VERSION>
        comment: Application version, from which user makes requests (Optional)
      - name: X-Platform
        example: <USER_PLATFORM>
        comment: Platform, from which user makes requests (Optional)
